### ISSUE TITLE
Create a jeykll theme blog 

### ISSUE THREAD

**Issue by gauthamzz** [gostudent/Letsgo#1]

**Comment by mubaris** [comment]
Select theme from this [site](http://jekyllthemes.org/)

**Comment by mubaris** [comment]
Some of the good themes

1) [dactl](http://jekyllthemes.org/themes/dactl/)
2) [Chalk](http://jekyllthemes.org/themes/chalk/)
3) [Webjeda Ashwath](http://jekyllthemes.org/themes/webjeda-ashwath/)

You are not restricted to these themes. You can choose any theme from the above site

**Comment by rahulkumaran** [comment]
What are the things that you exactly expect in the blog?

**Comment by gauthamzz** [comment]
we want are planning to have something like questions and answers.

So an article heading should be there and solution of that. A simple theme will do now.

**Comment by marshallKR7** [comment]
@gauthamzz  ,can we create blog on any topic or any specific one? I mean exactly what we have to show in blog?

**Comment by gauthamzz** [comment]
you dont need to show anything now,just a starter template is fine

**Comment by marshallKR7** [comment]
Okk then I want to do it.

**Comment by marshallKR7** [comment]
[https://marshallkr7.github.io/emerald/](url)
@gauthamzz  Is this sufficient starter template or do I have to add something more?

**Comment by marshallKR7** [comment]
https://marshallkr7.github.io/emerald/
@gauthamzz  Is this sufficient starter template or I need to add something more?
Also I have changed dates of the post otherwise they were coming in chronological order due to which last post added was coming at first.

**Comment by gauthamzz** [comment]
yeah it looks good.
you may send pr
