### ISSUE TITLE
Fix theme issues

### ISSUE THREAD

**Issue by gauthamzz** [gostudent/Letsgo#4]

**Comment by namantw** [comment]
I want to do this

**Comment by gauthamzz** [comment]
cool assinged to you @namantw

**Comment by gauthamzz** [comment]
can you update on this ?

**Comment by namantw** [comment]
@gauthamzz I have some experience with Jekyll, I think the whole structure needs to be changed, i.e., I can make a completely new working Jekyll website. Should I go for that?

**Comment by gauthamzz** [comment]
yeah its fine. change the theme to https://github.com/myJekyll/jasper2

**Comment by namantw** [comment]
I am on it

**Comment by gauthamzz** [comment]
do this asap. everyother issue depends on this.

**Comment by namantw** [comment]
Okay, just 1 hour please!

**Comment by namantw** [comment]
@gauthamzz sir, github pages goes not support Jekyll themes with `_plugins`, so getting jasper2 to work with github would be complicated

**Comment by gauthamzz** [comment]
Try anyother theme. Its okay .

**Comment by namantw** [comment]
Never mind I got it working :P live here : https://namantw.github.io/test/
![image](https://user-images.githubusercontent.com/31323328/34888455-5ed6cbbe-f7f0-11e7-830d-9610f4198233.png)
![image](https://user-images.githubusercontent.com/31323328/34888474-70046e3c-f7f0-11e7-864f-d413749f8f0d.png)

PR on its way :)

**Comment by namantw** [comment]
@gauthamzz Do we have a Facebook / twitter page ? please send the links if there is one, or will you add them later?

**Comment by gauthamzz** [comment]
send pr. we have twitter @gostudents

**Comment by namantw** [comment]
@gauthamzz https://github.com/gostudent/Letsgo/pull/7
