### ISSUE TITLE
Star This Repo

### ISSUE THREAD

**Issue by mubaris** [gostudent/Letsgo#6]
Post Screenshots

**Comment by arpitmisraw** [comment]
![screenshot_2018-01-11-23-17-26-180_com android chrome](https://user-images.githubusercontent.com/32339738/34838883-bd0ebf28-f725-11e7-9b33-0875bae2a1e4.png)

**Comment by GOVINDDIXIT** [comment]
![captureg](https://user-images.githubusercontent.com/32304546/34839011-297d5b56-f726-11e7-8c07-9112a77daca8.PNG)

**Comment by amriteshbhaskar** [comment]
![letsgo](https://user-images.githubusercontent.com/34058250/34839080-6e183ac4-f726-11e7-98d8-8f71c4ed93ea.png)

**Comment by 16priyesh** [comment]
![image](https://user-images.githubusercontent.com/28901008/34839378-6ec765a2-f727-11e7-921e-08d603e2953a.png)

**Comment by ananya** [comment]
![a](https://user-images.githubusercontent.com/33188930/34839449-a12b0576-f727-11e7-9299-fe9b38994b42.png)

**Comment by YashRE42** [comment]
![image](https://user-images.githubusercontent.com/33805964/34839426-9450aeaa-f727-11e7-937f-46782e13982e.png)

**Comment by marshallKR7** [comment]
![screenshot-2018-1-11 gostudent letsgo](https://user-images.githubusercontent.com/28799332/34839892-3abb9cfe-f729-11e7-8baf-6506845c5fa9.png)

**Comment by adityaraj-xtc** [comment]
![2](https://user-images.githubusercontent.com/34164978/34840305-8e96c7da-f72a-11e7-9cf4-bfea46dc5b7a.png)

**Comment by ak5hit** [comment]
![image](https://user-images.githubusercontent.com/35285444/34840876-60724b8e-f72c-11e7-90d1-5a010beb52e8.png)

**Comment by namantw** [comment]
![image](https://user-images.githubusercontent.com/31323328/34840883-69d1114c-f72c-11e7-8374-58b0ccd1a99d.png)

**Comment by rahulkumaran** [comment]
![screenshot from 2018-01-12 00-11-12](https://user-images.githubusercontent.com/26206171/34841107-1f872a4e-f72d-11e7-9606-9d046ac881ae.png)

**Comment by nikki1016** [comment]
![star2](https://user-images.githubusercontent.com/26041681/34841664-05737336-f72f-11e7-9889-1eaba831abb0.png)

**Comment by prathamprakash29** [comment]
![image](https://user-images.githubusercontent.com/30841366/34846252-90f674cc-f73d-11e7-9611-a4bd7fba0adf.png)

**Comment by strikertanmay** [comment]
![screenshot from 2018-01-12 02-24-16](https://user-images.githubusercontent.com/32292953/34846924-bf871f6a-f73f-11e7-9885-820649abae93.png)

**Comment by AK-007** [comment]
![screenshot 58](https://user-images.githubusercontent.com/26346816/34848492-fdabbca6-f744-11e7-8c20-0f92cdb6d03d.png)

**Comment by surasnayak** [comment]
done
![screenshot from 2018-01-12 08-44-10](https://user-images.githubusercontent.com/21239888/34848935-aeeb62fe-f746-11e7-9320-553dbe648ef3.png)

**Comment by Tlazypanda** [comment]
![image](https://user-images.githubusercontent.com/33183263/34866247-f2bb9c5a-f7a1-11e7-9272-e873989da6db.png)

**Comment by vvvinamer** [comment]
![screenshot 36](https://user-images.githubusercontent.com/35339278/34868852-230811aa-f7ab-11e7-81d1-3316359bdf97.png)

**Comment by AlphaCholera** [comment]
![screenshot from 2018-01-12 22-18-02](https://user-images.githubusercontent.com/33174671/34872790-6a9c2422-f7b8-11e7-8f1c-ce1e93e54535.png)

**Comment by maverick0004** [comment]
![screenshot from 2018-01-12 16-51-51](https://user-images.githubusercontent.com/33194760/34872920-ed0fe13c-f7b8-11e7-99d9-8188a1e7b222.png)

**Comment by RohanShekhawat** [comment]
![capture](https://user-images.githubusercontent.com/34987773/34889018-7ef5c09c-f7f2-11e7-85b3-a65d69995d41.PNG)

**Comment by aadixiiita** [comment]
![screenshot_20180113-214514](https://user-images.githubusercontent.com/34688457/34907852-1fa20ace-f8ab-11e7-8adb-c370c36b259a.png)

**Comment by anandwana001** [comment]
![screenshot_2018-01-14-03-17-27-338_com android chrome](https://user-images.githubusercontent.com/25057618/34910375-87f94d66-f8d9-11e7-9b8e-792ca77490c4.png)
